changelog_type: 'pull_request' # 'commit_message' or 'pull_request'
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: true
include_unlabeled_changes: true
unlabeled_group_title: 'Further Changes'
pull_request_title_regex: '^Release'
version_regex: 'v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\)'
exclude_labels:
  - bot
  - dependabot
  - ci
group_config:
  - title: 🛠 Breaking Changes 🛠
    labels:
      - breaking change
  - title: New Features
    labels:
      - enhancement
  - title: TFLite model
    labels:
      - tflite model
  - title: Bug Fixes
    labels:
      - bug