changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-bot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: New TFLite Model
      labels:
        - tflite model
    - title: Bugfixes
      labels:
        - bug
    - title: Further Changes
      labels:
        - "*"