name: 🐞 Bug Report
description: File a bug report
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        For discussions and requests please use the discussion section!
  - type: textarea
    attributes:
      label: Description
      description: Please describe, what happend, what did you expect to happen and how can it be reproduced
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Please provide any relevant logs (WebUI `System > Log Viewer` or console log). The content will be automatically formatted
      render: shell
  - type: input
    attributes:
      label: Firmware Version
      description: Which firmware version are you using? (WebUI `System > Info > Build > Firmware Version` or check console log during boot)
    validations:
      required: true
