on:
  push:
    branches:
      - develop
      - build-workflow

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
          draft-pull-request: false
          pull-request-header: ':robot: Gather changes for upcomming release'
          changelog-path: CHANGELOG.md
          changelog-types: '[
                             {"type":"feat","section":"Features","hidden":false},
                             {"type":"fix","section":"Bug Fixes","hidden":false},
                             {"type":"refactor","section":"Refactoring / Style Changes","hidden":false},
                             {"type":"chore","section":"Other Changes","hidden":false}
                            ]'
          skip-github-release: false

  create_release:
    runs-on: ubuntu-latest
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
        token: ${{secrets.GH_TOKEN}}
    - name: Download changelog
      uses: actions/download-artifact@v3
      with:
        name: changelog
        path: ../changelog
    - uses: ncipollo/release-action@v1
      name: Create release
      with:
        bodyFile: ../changelog/changelog.md
        draft: true
        name: ${{ needs.release-please.outputs.version }}
        tag: ${{ needs.release-please.outputs.version }}


#########################################################################################
## Prepare and create release
#########################################################################################
  release: 
    runs-on: ubuntu-latest
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}

    # Sets permissions of the GITHUB_TOKEN to allow updating the branches
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3.53

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if the artifact is from a different repo
        # Required, if the repo is private a Personal Access Token with `repo` scope is needed or GitHub token in a job where the permissions `action` scope set to `read`
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Optional, workflow file name or ID
        # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
        workflow: build.yaml

    - name: Set variables
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "branch=$(echo ${{ github.ref_name }} | tr / __)" >> $GITHUB_OUTPUT

    - name: Prepare artifacts for release
      run: |
        rm -rf release
        mkdir -p release

        # AI-on-the-edge-device__OTA-update__*.zip (e.g. "AI-on-the-edge-device__OTA-update__v16.0.0.zip")
        cd ./update
        zip -r ../release/AI-on-the-edge-device__update__SLFork__${{ steps.vars.outputs.branch }}.zip .
        

        # AI-on-the-edge-device__manual-setup__*.zip (e.g. "AI-on-the-edge-device__manual-setup__v16.0.0.zip")
        cd ./manual_setup
        zip -r ../release/AI-on-the-edge-device__manual-setup__SLFork__${{ steps.vars.outputs.branch }}.zip .


        # AI-on-the-edge-device__remote-setup__*.zip (e.g. "AI-on-the-edge-device__remote-setup__v16.0.0.zip")
        cd ./remote_setup
        zip -r ../release/AI-on-the-edge-device__remote-setup__SLFork__${{ steps.vars.outputs.branch }}.zip .
        
        
        # AI-on-the-edge-device__debug-files__*.zip (e.g. "AI-on-the-edge-device__debug-files__v16.0.0.zip)"
        cd ./debug
        zip -r ../release/AI-on-the-edge-device__debug-files__SLFork__${{ steps.vars.outputs.branch }}.zip .
           
    # Release notes will be extracted from changelog (Release notes updated by release-please action)
    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v1
      with:
          changelog_file: CHANGELOG.md

    # Releases should only be created by tagging the last commit (Tag commit performed by release-please action)
    # All artifacts in firmware folder pushed to the release
    - name: Release
      uses: softprops/action-gh-release@v1
      # Note:
      # If you get the error "Resource not accessible by integration",
      # The access rights are not sufficient, see
      # https://github.com/softprops/action-gh-release/issues/232#issuecomment-1131379440
      with:
        name: ${{ needs.release-please.outputs.version }}
        tag: ${{ needs.release-please.outputs.version }}
        body: ${{ steps.extract-release-notes.outputs.release_notes }}
        files: |
          release/*
