name: Update Web Installer

on:
  workflow_dispatch:


jobs:
  update-webinstaller:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plat:
         - esp32cam
         - xiao-esp32s3-sense

    # Sets permissions of the GITHUB_TOKEN to allow downloading artifacts
    permissions:
      actions: read
      contents: write

    steps:
    - name: Set variables
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "branch=$(echo ${{ github.ref_name }} | tr / __)" >> $GITHUB_OUTPUT

    - name: Pull artifacts
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        regex: true
        file: "AI-on-the-edge-device.*.zip"
        target: './artifacts/'

    - name: Switch branch
      run: |
        git switch gh-pages

    - name: Prepare data
      run: |
        echo "Updating firmware files..."
        rm -rf ./firmware/${{ matrix.plat }}/
        unzip ./artifacts/*.zip
        cp -f "./artifacts/AI-on-the-edge-device__${{ matrix.plat }}__SLFork_${{ steps.vars.outputs.branch }}_(${{ steps.vars.outputs.sha_short }})/*.bin" "./firmware/${{ matrix.plat }}/"
        echo "Updating index and manifest file..."
        sed -i 's/$VERSION/${{ needs.prepare-release.outputs.tag_name }}/g' index.html
        sed -i 's/$VERSION/${{ needs.prepare-release.outputs.tag_name }}/g' manifest_${{ matrix.plat }}.json

    - name: Commit data
      shell: pwsh
      run: |
        & git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        & git config --local user.name "github-actions[bot]"
        & git add .
        & git diff HEAD --exit-code | Out-Null
        if ($LASTEXITCODE -ne 0)
        {
          & git commit -m "Update firmware"
          & git push origin testcommit
        }
